source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "Delapouite/kakoune-colors"
plug "andreyorst/fzf.kak"

colorscheme desertex

add-highlighter global/ number-lines
